# This fileis written in ruby
# Uncomment the next line to define a global platform for your project
# define the minimum ios version that u want your app to run on. some feature requires ios 13
platform :ios, '9.0'

target 'Flash Chat iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flash Chat iOS13
    
    pod 'CLTypingLabel'
    
end
